# Generated by Django 6.0 on 2026-02-27 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Volunteer Assigned'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('purpose', models.CharField(choices=[('medical', 'Medical Assistance'), ('emergency', 'Emergency Help'), ('daily', 'Daily Living Support'), ('mobility', 'Mobility Support'), ('other', 'Other')], max_length=20)),
                ('purpose_description', models.TextField(blank=True, null=True)),
                ('chronic_disease', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('mobility_issue', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('recent_fall', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('emergency_visits', models.PositiveIntegerField(default=0)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elder_requests', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
