# Generated by Django 6.0 on 2026-03-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elderrequest',
            name='age',
        ),
    ]
