# Generated by Django 6.0 on 2026-03-05 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('elder', 'Elder'), ('volunteer', 'Volunteer'), ('staff', 'Thamar Staff')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('preferred_language', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('health_support', models.JSONField(blank=True, null=True)),
                ('communication_mode', models.CharField(max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elder', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ThamarStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('verification', 'Verification'), ('complaints', 'Complaints'), ('operations', 'Operations')], max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(blank=True, null=True)),
                ('availability', models.JSONField(blank=True, null=True)),
                ('experience_level', models.CharField(max_length=50)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='verification_docs/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to='accounts.profile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_volunteers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
