# Generated by Django 6.0 on 2026-03-05 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='volunteer_address/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='volunteer_ids/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
