# Generated by Django 6.0 on 2026-03-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_volunteer_address_proof_alter_volunteer_id_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('link_sent', 'Verification Link Sent'), ('submitted', 'Documents Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
