# Generated by Django 6.0 on 2026-02-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elder',
            name='age',
        ),
    ]
