# Generated by Django 6.0 on 2026-03-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_volunteer_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
