# Generated by Django 6.0 on 2026-03-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_volunteer_is_verified_volunteer_id_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('elder', 'Elder'), ('volunteer', 'Volunteer'), ('staff', 'Thamar Staff')], max_length=20),
        ),
    ]
