# Generated by Django 6.0 on 2026-03-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThamarStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('verification', 'Verification'), ('complaints', 'Complaints'), ('operations', 'Operations')], max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.profile')),
            ],
        ),
    ]
